//
//  Country.swift
//  LifePlus
//
//  Created by Roberto Mascarenhas on 02/10/23.
//

import Foundation



enum Country: String, CaseIterable, Identifiable {
    var id: Country{self}
    case Afeganistao = "🇦🇫 Afeganistão"
    case AfricaDoSul = "🇿🇦 África do Sul"
    case Albania = "🇦🇱 Albânia"
    case Alemanha = "🇩🇪 Alemanha"
    case Angola = "🇦🇴 Angola"
    case AraviaSaudita = "🇸🇦 Arábia Saudita"
    case Argelia = "🇩🇿 Argélia"
    case Argentina = "🇦🇷 Argentina"
    case Armenia = "🇦🇲 Armênia"
    case Australia = "🇦🇺 Austrália"
    case Austria = "🇦🇹 Áustria"
    case Azerbaijao = "🇦🇿 Azerbaijão"
    case Bangladesh = "🇧🇩 Bangladesh"
    case Belgica = "🇧🇪 Bélgica"
    case Bermudas = "🇧🇲 Bermudas"
    case Bolivia = "🇧🇴 Bolívia"
    case Brasil = "🇧🇷 Brasil"
    case Burundi = "🇧🇮 Burundi"
    case CaboVerde = "🇨🇻 Cabo Verde"
    case Camaroes = "🇨🇲 Camarões"
    case Camboja = "🇰🇭 Camboja"
    case Canada = "🇨🇦 Canadá"
    case Cazaquistao = "🇰🇿 Cazaquistão"
    case CentroAfricana = "🇨🇫 Centro-Africana"
    case Chade = "🇹🇩 Chade"
    case Chile = "🇨🇱 Chile"
    case China = "🇨🇳 China"
    case Chipre = "🇨🇾 Chipre"
    case Cingapura = "🇸🇬 Cingapura"
    case Colombia = "🇨🇴 Colômbia"
    case CongoDemRep = "🇨🇩 Congo"
    case CoreiaDoNorte = "🇰🇵 Coréia do Norte"
    case CoreiaDoSul = "🇰🇷 Coréia do Sul"
    case CostaDoMafim = "🇨🇮 Costa do Marfim"
    case CostaRica = "🇨🇷 Costa Rica"
    case Croacia = "🇭🇷 Croácia"
    case Cuba = "🇨🇺 Cuba"
    case Dinamarca = "🇩🇰 Dinamarca"
    case Egito = "🇪🇬 Egito"
    case ElSalvador = "🇸🇻 El Salvador"
    case EmiradosArabes = "🇦🇪 Emirados Árabes Unidos"
    case Equador = "🇪🇨 Equador"
    case Espanha = "🇪🇸 Espanha"
    case EstadosUnidos = "🇺🇸 Estados Unidos"
    case Estonia = "🇪🇪 Estônia"
    case Etiopia = "🇪🇹 Etiópia"
    case Filipinas = "🇵🇭 Filipinas"
    case Finlandia = "🇫🇮 Finlândia"
    case Franca = "🇫🇷 França"
    case Gana = "🇬🇭 Gana"
    case Georgia = "🇬🇪 Geórgia"
    case Grecia = "🇬🇷 Grécia"
    case GuineEquatorial = "🇬🇶 Guiné Equatorial"
    case GuineBissau = "🇬🇼 Guiné-Bissau"
    case Haiti = "🇭🇹 Haiti"
    case HongKong = "🇭🇰 Hong Kong"
    case Hungria = "🇭🇺 Hungria"
    case Ieemen = "🇾🇪 Iêmen"
    case India = "🇮🇳 Índia"
    case Indonesia = "🇮🇩 Indonésia"
    case Iran = "🇮🇷 Irã"
    case Irlanda = "🇮🇪 Irlanda"
    case Islandia = "🇮🇸 Islândia"
    case Israel = "🇮🇱 Israel"
    case Italia = "🇮🇹 Itália"
    case Jamaica = "🇯🇲 Jamaica"
    case Japao = "🇯🇵 Japão"
    case Laos = "🇱🇦 Laos"
    case Letonia = "🇱🇻 Letônia"
    case Liechtenstein = "🇱🇮 Liechtenstein"
    case Lituania = "🇱🇹 Lituânia"
    case Luxemburgo = "🇱🇺 Luxemburgo"
    case Macau = "🇲🇴 Macau"
    case Madagascar = "🇲🇬 Madagascar"
    case Malasia = "🇲🇾 Malásia"
    case Mali = "🇲🇱 Mali"
    case Malta = "🇲🇹 Malta"
    case Marrocos = "🇲🇦 Marrocos"
    case Mauricio = "🇲🇺 Maurício"
    case Mexico = "🇲🇽 México"
    case Mocambique = "🇲🇿 Moçambique"
    case Montenegro = "🇲🇪 Montenegro"
    case Nepal = "🇳🇵 Nepal"
    case Niger = "🇳🇪 Níger"
    case Nigeria = "🇳🇬 Nigéria"
    case Noruega = "🇳🇴 Noruega"
    case NovaZelandia = "🇳🇿 Nova Zelândia"
    case Oman = "🇴🇲 Omã"
    case PaisesBaixos = "🇳🇱 Países Baixos"
    case Panama = "🇵🇦 Panamá"
    case PapuaNovaGuine = "🇵🇬 Papua-Nova Guiné"
    case Paquistao = "🇵🇰 Paquistão"
    case Paraguai = "🇵🇾 Paraguai"
    case Peru = "🇵🇪 Peru"
    case Polonia = "🇵🇱 Polônia"
    case PortoRico = "🇵🇷 Porto Rico"
    case Portugal = "🇵🇹 Portugal"
    case Quenia = "🇰🇪 Quênia"
    case ReinoUnido = "🇬🇧 Reino Unido"
    case Romenia = "🇷🇴 Romênia"
    case Ruanda = "🇷🇼 Ruanda"
    case Russia = "🇷🇺 Rússia"
    case SaoMarino = "🇸🇲 São Marino"
    case SaoTomeEPrincipe = "🇸🇹 São Tomé e Príncipe"
    case Senegal = "🇸🇳 Senegal"
    case SerraLeoa = "🇸🇱 Serra Leoa"
    case Servia = "🇷🇸 Sérvia"
    case Somalia = "🇸🇴 Somália"
    case Sudao = "🇸🇩 Sudão"
    case SudaoDoSul = "🇸🇸 Sudão do Sul"
    case Suecia = "🇸🇪 Suécia"
    case Suica = "🇨🇭 Suíça"
    case Tailandia = "🇹🇭 Tailândia"
    case Tcheca = "🇨🇿 Tchéquia"
    case TimorLeste = "🇹🇱 Timor-Leste"
    case Turquia = "🇹🇷 Turquia"
    case Ucrania = "🇺🇦 Ucrânia"
    case Uruguai = "🇺🇾 Uruguai"
    case Venezuela = "🇻🇪 Venezuela"
    case Vietnam = "🇻🇳 Vietnã"
    case Zambia = "🇿🇲 Zâmbia"
}
